# Generated by Django 2.1.2 on 2018-10-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(max_length=150),
        ),
    ]
